addSbtPlugin("org.scalariform" % "sbt-scalariform"  % "1.8.2")
addSbtPlugin("com.jsuereth"    % "sbt-pgp"          % "1.1.2")
addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"    % "0.9.0")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"     % "2.0")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"     % "0.14.9")
addSbtPlugin("com.typesafe"    % "sbt-mima-plugin"  % "0.3.0")
